###########
# ENV VARS:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - GITHUB_TOKEN (default)
###########

name: Publish Docker Image

on:
  push:
    paths:
      - 'release-versions/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get current repository
        uses: actions/checkout@v4

      - name: Get the version
        id: vars
        run: echo "tag=$(cat release-versions/strapi-latest.txt)" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (default => debian)
        uses: docker/build-push-action@v6
        with:
          context: ./images/strapi-debian
          platforms: linux/amd64
          build-args: |
            STRAPI_VERSION=${{steps.vars.outputs.tag}}
            NODE_VERSION=18
            NODE=node
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/strapi:latest

      - name: Build (alpine)
        uses: docker/build-push-action@v6
        with:
          context: ./images/strapi-alpine
          platforms: linux/amd64
          build-args: |
            STRAPI_VERSION=${{ steps.vars.outputs.tag }}
            NODE_VERSION=18
            NODE=node
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }}-alpine
            ${{ secrets.DOCKER_USERNAME }}/strapi:latest-alpine
      
      - name: Build (default => debian arm64)
        uses: docker/build-push-action@v6
        with:
          context: ./images/strapi-debian
          platforms: linux/arm64
          build-args: |
            STRAPI_VERSION=${{steps.vars.outputs.tag}}
            NODE_VERSION=18
            NODE=arm64v8/node
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }}-arm64
            ${{ secrets.DOCKER_USERNAME }}/strapi:latest-arm64

      - name: Build (alpine arm64)
        uses: docker/build-push-action@v6
        with:
          context: ./images/strapi-alpine
          platforms: linux/arm64
          build-args: |
            STRAPI_VERSION=${{ steps.vars.outputs.tag }}
            NODE_VERSION=18
            NODE=arm64v8/node
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }}-alpine-arm64
            ${{ secrets.DOCKER_USERNAME }}/strapi:latest-alpine-arm64

      - name: Create Release in GitHub
        id: create_release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{steps.vars.outputs.tag}}
          release_name: Release ${{steps.vars.outputs.tag}}
          body: strapi v${{steps.vars.outputs.tag}}
